#!/bin/sh
echo "restarting application..."
echo "  installing node dependencies..."
npm install
echo "  done"
echo "  restarting server..."
forever restart log-browser.js
echo "  done"
echo "application restarted!"