#!/bin/sh
echo "restarting application..."
echo "  installing node dependencies..."
npm install
echo "  done"
echo "  restarting server..."
cd ~/apps/log-browser
forever restart log-browser.js
cd ~
echo "  done"
echo "application restarted!"